services:
  - type: web
    name: autoforms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: ENV
        value: production
      - key: DEBUG
        value: false
      - key: PYTHONPATH
        value: .
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
    healthCheckPath: /health